services:
  kong:
      image: kong
      volumes:
        - ./config/kong.yaml:/etc/kong/kong.yaml
      container_name: kong
      environment:
        KONG_DATABASE: off
        KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
        KONG_ADMIN_LISTEN: 0.0.0.0:8001
        KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
        KONG_ADMIN_GUI_URL: http://localhost:8002
      ports:
        - "8000:8000/tcp"
        - "8443:8443/tcp"
        - "8001:8001/tcp"
        - "8002:8002/tcp"
        - "8444:8444/tcp"
        - "127.0.0.1:7990:8001/tcp"
        # KONG_DATABASE: postgres
        # KONG_PG_HOST: kong-database
        # KONG_PG_PASSWORD: kong
        # KONG_PASSWORD: kongadmin
        # KONG_ADMIN_LISTEN: 0.0.0.0:8001
        # KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
        # KONG_ADMIN_GUI_URL: http://localhost:8002
