_format_version: "3.0"
services:
  - name: mockbin-service
    url: http://mockbin.org
    connect_timeout: 60000
    enabled: true
    host: mockbin.org
    port: 80
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - name: mockbin-route
        paths:
          - /mock
        https_redirect_status_code: 426
        path_handling: v0
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
      - http://mockbin.com
      methods:
      - GET
      - POST
      headers:
      - Accept
      - Accept-Version
      - Content-Length
      - Content-MD5
      - Content-Type
      - Date
      - X-Auth-Token
      exposed_headers:
      - X-Auth-Token
      credentials: true
      max_age: 3600
