_format_version: "3.0"
services:
  - name: mockbin-service
    url: http://mockbin.org
    connect_timeout: 60000
    enabled: true
    host: mockbin.org
    port: 80
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - name: mockbin-route
        paths:
          - /mock
        https_redirect_status_code: 426
        path_handling: v0
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
      - http://mockbin.com # Allows to query localhost:8000/mock only from these origins
      methods:
      - GET
      - POST
      headers:
      - Accept
      - Accept-Version
      - Content-Length
      - Content-MD5
      - Content-Type
      - Date
      - X-Auth-Token
      exposed_headers:
      - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: rate-limiting
    service: mockbin-service
    config:
      minute: 3
      hour: 10000
      policy: local

  - name: ip-restriction
    service: mockbin-service
    config:
      allow:
      # - 54.13.21.1 # This is a random address - if you have it enable, you should not be able to access , http://localhost:8000/mock
      - 172.18.0.0/24 # This should allow my ip "range" - /24 CIDR

